package com.fleetpulse.entity;

/**
 * Types of maintenance alerts generated by the health analysis engine.
 */
public enum AlertType {
    OVERHEATING,
    HIGH_VIBRATION,
    LOW_FUEL,
    ABNORMAL_PRESSURE,
    HIGH_ENGINE_HOURS
}
