package com.fleetpulse.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Represents a maintenance alert generated by the health analysis engine.
 *
 * <p>Alerts are created automatically when telemetry readings breach defined
 * thresholds. Each alert is tied to a specific machine and can be resolved
 * once maintenance has been performed.</p>
 */
@Entity
@Table(name = "maintenance_alerts", indexes = {
        @Index(name = "idx_alert_machine", columnList = "machine_id"),
        @Index(name = "idx_alert_resolved", columnList = "resolved"),
        @Index(name = "idx_alert_severity", columnList = "severity")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MaintenanceAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "machine_id", nullable = false)
    private Machine machine;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private AlertType alertType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Severity severity;

    @Column(nullable = false, length = 500)
    private String message;

    @Column(nullable = false)
    private Boolean resolved;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        if (this.resolved == null) {
            this.resolved = false;
        }
    }
}
